### ISSUE TITLE
Custom step

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#144]
Extracted from https://github.com/iterative/dvclive/pull/142#pullrequestreview-738942719.

- What is the intended use case for a custom step?
- Should it overwrite existing values for the same step (it doesn't)?
- Should results be ordered by write time or step (they are ordered by write time)?
- Why set custom steps at the metric level with dvclive.log(step=n) since the step value should probably apply to all metrics?
- If I log one metric and then set a different step for a second metric, which step number should be used for the first metric (it will have a different step in the tsv and the summary json)?

**Comment by pared** [comment]
> - What is the intended use case for a custom step?  

Intended use case was for situation when we log every n-steps, though I have to admit that providing it in log is unfortunate. We should have something that could scope whole step.

> Maybe allowing to set the custom step at the next_step level would make more sense.

I wouldn't go this way, because it will make users introduce logic calculating the next step value in the current loop iteration, which might be error prone (eg user changes range args, but forgets to update `next_step` part).

The simplest way would be to create `dvclive.set_step`.
Another way to do that could be to create some kind of wrapper for generators (related #68), but in that case we could have problems determining what step actually is (eg wrapping `range(10)` is easy, but what about `enumerate(range(10))`.

**Comment by dberenbaum** [comment]
> In which scenario would a user want to call `dvclive.log` twice with the same custom `step`?

I can only think of an interactive scenario where I wrote the wrong step value and later want to correct it. Not a major concern.

> The only scenario I can think of where time/step order differs would be if the user calls `dvclive.log()` with a `step` value lower than the previously used. Not sure if we should even allow that.

Good points. Again, not a major concern.

> The simplest way would be to create `dvclive.set_step`.

Seems simple and effective. Probably better to go this way and give users control (the Python way) rather than figure out "correct" behavior for every scenario.
