### ISSUE TITLE
next_step() needs log()

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvclive#232]
```python
import dvclive

live = dvclive.Live(resume=True)
while (epoch := live.get_step()) < 10:
  print(epoch)
  live.log("epoch", epoch)  # need to log at least one thing for `next_step` to work
  live.next_step()
```

- current: `dvclive.json` is stuck on `step: 0` if we remove the `live.log()` command.
- expected: `step: 10` even without `live.log()`

Related: https://github.com/iterative/cml.dev/issues/207

**Comment by daavoo** [comment]
The `step` is being correctly updated internally (even if you remove the `log` call, the while loop breaks) but the updates are not being dumped to the summary file `dvclie.json`. This is because we moved the summary updates to `log` calls (https://github.com/iterative/dvclive/issues/145). 

Not sure what to do here. The summary is intended to track _logged_ scalars and we just include `step` for convenience 🤔 

cc @dberenbaum

**Comment by casperdcl** [comment]
Seems odd to do this. if there are multiple things to log per iteration, you dump multiple times?

- Seems better to dump only on `next_step()`
- Could also make configurable default `log(..., force_write=False)`
- Could make `next_step()` internally use `log("step", ..., force_write=True)`

**Comment by dberenbaum** [comment]
@casperdcl Why do you want to use `next_step()` without `log()`? I don't see a problem doing so, but I'm confused how it's useful.

**Comment by casperdcl** [comment]
Full context is `step` is the only thing that is required in order to resume interrupted training (notice the example above uses `get_step()`) - we don't need to log `loss` nor any other metrics.

**Comment by dberenbaum** [comment]
We probably need to decouple `log()` from setting the step to resolve this issue. 

@casperdcl I moved the optimization to #238.

Both are good points that are largely due to changes in the codebase over time and should probably be changed now AFAIK.

**Comment by dberenbaum** [comment]
Actually, I think we just need to call `make_summary()` always during `set_step()` (ignoring #238).
