### ISSUE TITLE
Configure DVC experiment from DVCLive

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#311]
Follow up to #310

> Before creating the experiment ref, DVCLive should write to a `dvc.yaml` file inside the `Live` directory, which should configure parameters, metrics, and plots logged by DVCLive. This could happen either during logging or at the end before creating the experiment ref. Depends on https://github.com/iterative/dvc/issues/8371.
>
> If DVCLive is run inside of a DVC pipeline, can we detect and skip all of this functionality for now? Long term, it would be nice for DVC pipelines to be able to support this DVCLive-configured `dvc.yaml`.

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/issues/310#issuecomment-1259774535_

**Comment by dberenbaum** [comment]
> If DVCLive is run inside of a DVC pipeline, can we detect and skip all of this functionality for now? Long term, it would be nice for DVC pipelines to be able to support this DVCLive-configured `dvc.yaml`.

Not sure we need to actually skip writing to `dvc.yaml` in pipelines. Probably we need an option to choose whether to skip, since if someone has a custom plots configuration, for example, they won't want to use the auto-generated `dvc.yaml`.

**Comment by daavoo** [comment]
I guess we could have DVCLive auto-generate names for now (related to https://github.com/iterative/vscode-dvc/issues/2457) if it's easier than revisiting how exp names are assigned, but it might be better to track changes across the entire repo instead of only in `dvc.lock`.

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/pull/8408#discussion_r1014642023_
