### ISSUE TITLE
dvc: Configure sklearn plots in generated `dvc.yaml`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#371]
Follow up: configure sklearn plots

_Originally posted by @daavoo in https://github.com/iterative/dvclive/pull/366#discussion_r1036220642_

**Comment by mattseddon** [comment]
👍🏻 

I just committed the auto-generated `dvclive/dvc.yaml` against the VS Code demo project ([here](https://github.com/iterative/vscode-dvc-demo/pull/27/files)) and ended up with this:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/37993418/206330660-f1542b70-c398-4475-a87c-ac90a04754e7.png">


Not sure why the file was generated in an existing project. Perhaps because I had never run an experiment against that clone?
