### ISSUE TITLE
save_dvc_exp: warn and continue if save fails

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#466]
Right now, if there is a problem with saving the experiment (like an invalid `dvc.yaml`), the script fails with an error. Instead, it should succeed and warn that the experiment failed to save.

**Comment by daavoo** [comment]
It turns out that `save_dvc_exp=True` when combined with `dvc repro` also fails because of a lock error. 

Addressing this issue would make it to just not save the experiment but I don't know if that's enough or we should try to do something else for that case (try to make it work, a more explicit warning, make it ignore `save_dvc_exp` like `dvc exp run` does)

**Comment by dberenbaum** [comment]
> Addressing this issue would make it to just not save the experiment but I don't know if that's enough or should we try to do something else for that case (try to make it work, a more explicit warning, make it ignore `save_dvc_exp` like `dvc exp run` does)

This should be enough until we know better whether there are valid workflows for `dvc repro` + `dvc_exp_save`.
