### ISSUE TITLE
studio: `STUDIO_REPO_URL` needs to be set to live share experiments run from the queue

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvclive#485]
Noticed when working on https://github.com/iterative/vscode-dvc/pull/3398. In order to live share experiments that are running in the queue I have to start the queue (`dvc queue start`) with not only the `STUDIO_TOKEN` but also `STUDIO_REPO_URL`. This seems to be caused by `git ls-remote --get-url` not working for experiments that are being run from the queue. It appears that the remote is not respected in the created temp directory. E.g:

```console
/.dvc/tmp/exps/tmpayme39b7 @950c246e !2 ❯ git ls-remote --get-url
fatal: No remote configured to list refs from.
```

Not sure if this is expected behaviour or not. From what I can see `STUDIO_REPO_URL` is no longer mentioned in the [docs](https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots).  Happy to close and reopen elsewhere if this is not the correct place for this issue 🙏🏻.

**Comment by daavoo** [comment]
Hei @mattseddon sorry for the lack of communication here. 

> Not sure if this is expected behaviour or not.

It is not expected but I commented in https://github.com/iterative/dvc/issues/8951#issuecomment-1418951057 that it could be considered a particular case of https://github.com/iterative/dvc/issues/5800 , which is already prioritized in DVC as part of https://github.com/iterative/dvc/issues/8972 .

Other issues were considered a higher priority because setting the env var can be used as a workaround for this one.

> From what I can see STUDIO_REPO_URL is no longer mentioned in the [docs](https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots).

I didn't realize that it was completely removed, as far as I remember I added a mention of `exp queue` requiring the env var.

> Happy to close and reopen elsewhere if this is not the correct place for this issue 🙏🏻.

It needs to be addressed on DVC repo, you can comment at https://github.com/iterative/dvc/issues/5800 or https://github.com/iterative/dvc/issues/8972

**Comment by daavoo** [comment]
Closing this one as there is no action to be taken in DVCLive

**Comment by dberenbaum** [comment]
@daavoo Is your suggestion is that the git remotes must be copied over during `exp run`?

**Comment by daavoo** [comment]
> @daavoo Is your suggestion is that the git remotes must be copied over during exp run?

I am not sure if it's better to copy `.git/config` or try to repurpose an existing mechanism we have to set env vars inside the exp

**Comment by dberenbaum** [comment]
Added to https://github.com/iterative/dvc/issues/9074.

**Comment by daavoo** [comment]
Should be fixed in https://github.com/iterative/dvc/pull/9161
