### ISSUE TITLE
log_sklearn_plot: exception when plot params are passed.

### ISSUE THREAD

**Issue by ocraft** [iterative/dvclive#812]
When plot params (title, x_label etc.) are passed, e.g.:

````python
from dvclive import Live

with Live() as live:
  y_true = [0, 0, 1, 1]
  y_pred = [1, 0, 1, 0]
  y_score = [0.1, 0.4, 0.35, 0.8]
  live.log_sklearn_plot("roc", y_true, y_score)
  live.log_sklearn_plot(
    "confusion_matrix", y_true, y_pred, name="cm.json", title="Test")
````

the exception "TypeError: got an unexpected keyword argument 'title'" is thrown.

It's because of this line in the log_sklearn_plot method:
````python
sklearn_kwargs = {
    k: v for k, v in kwargs.items() if k not in plot_config or k != "normalized"
}

````
The condition ````if k not in plot_config or k != "normalized"```` is always true for all params different that "normalized".

**Comment by dberenbaum** [comment]
Good catch! It looks like `normalized` doesn't even need to be included here since it's already added to `plot_config` above. I also don't see why `normalized` is in `kwargs` at all instead of being a named argument. And other `plot_config` options `title`, `x_label`, and `y_label` seem to be undocumented, and I'm not sure they are really needed. I would suggest making `normalized` a named argument when fixing this.

@ocraft Are you interested in submitting a PR?

**Comment by dberenbaum** [comment]
Interesting, thanks. The reason it passes for `confusion_matrix` is that plot doesn't actually call any sklearn method, which is where the error gets raised.
