### ISSUE TITLE
Feature request: allow nested metric values via slash in metric name

### ISSUE THREAD

**Issue by aguschin** [iterative/dvclive#95]
There are situations when we may want to group metric values, for example, in "train", "val", "test":
1. We may need this to select what columns we want to show in Studio (e.g., turn on / turn of metrics for "val" completely).
2. Later we also can group plots in Studio/Vscode extension, like it is done in W&B, for example.

If “name” in dvclive.log(name, value) happens to be like “one/two” should we create a subfolder “one” with a filename “two”? Right now it raises an error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'training_metrics/train/box_loss.tsv'
```

At the same time it should be handled in .json file with the final epoch - there we could have nested dictionaries.

It seems like wandb has a special way to handle this - maybe grouping metrics which starts with the same substring? Not sure how it works, actually.

**Comment by aguschin** [comment]
Е

**Comment by daavoo** [comment]
I was about to report this as a bug :sweat_smile: 

I found the exception unexpected as it breaks the [mmcv integration](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/dvclive.py) because some of the downstream repositories use `train/` and `val/` prefixes (i.e. [mmdetection](https://github.com/open-mmlab/mmdetection))
